### ISSUE TITLE
Server.js won't start

### ISSUE THREAD

**Issue by lyonsdave** [QlikPreSalesDACH/Qlik-Sense-Agent#1]
I have gone through the configuration add the server info to the three files that need to be modified as well as created the data connections to the App folder and postgres.  However when I try to run the server.js  I get the following:

C:\node\QSA>node server.js
C:\node\QSA\routes.js:70
                qsocks.Connect(target).then(global => {
                                                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\node\QSA\server.js:39:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by QlikPreSalesDACH** [comment]
For me it seems that node.js has a problem with the simplyfied notiation for the promise. Which version of node.js are you using?

We recommend to work with node.js 6.11.0.

Older versions of node.js may not support this notation.

To doublecheck that you could comment line 42 - 155 from the routes.js file.

**Comment by QlikPreSalesDACH** [comment]
Upgrade node.js to 6.11.2 solved the issue.
